 algoritmo "somar numeros"
 var
 N,soma,contador: inteiro
 inicio
 //solicita ao usuario o valor de N
 escreva ("digite um valor para N: ")
 LEIA (N)
 
 // inicializa vairiaveis
 contador <- 1
 soma <- 0
 // enquanto o contador for menor ou igual a N,faca:
 enquanto contador <= N faca
 soma <- soma + contador
 contador <- contador + 1
 fimenquanto
 // exibe o resultado a soma
escreva("a soma dos numeoros de 1 ate ", N, "e: ", soma)
fimalgoritmo
 

 
 
 